{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "4b3cbcd8_1d13e0eb",
        "filename": "tvix/eval/src/vm.rs",
        "patchSetId": 4
      },
      "lineNbr": 210,
      "author": {
        "id": 1000034
      },
      "writtenOn": "2022-10-02T16:21:08Z",
      "side": 1,
      "message": "This code should be unreachable for a correct compilation, right? I doubt `tail_call_value` can be safely called from a builtin, so maybe we should disallow it (and this case), e.g. by popping from the stack instead of taking an argument.",
      "revId": "3b7edd6e6bd5e11e10a1e41f1e6d01ed49142c1f",
      "serverId": "4fdfa107-4df9-4596-8e0a-1d2bbdd96e36"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "718cbba0_31106853",
        "filename": "tvix/eval/src/vm.rs",
        "patchSetId": 4
      },
      "lineNbr": 227,
      "author": {
        "id": 1000034
      },
      "writtenOn": "2022-10-02T16:21:08Z",
      "side": 1,
      "message": "We should probably also add a hint to the error message that `__functor` is required for sets to be called (like we do with `__toString` for coercions).",
      "revId": "3b7edd6e6bd5e11e10a1e41f1e6d01ed49142c1f",
      "serverId": "4fdfa107-4df9-4596-8e0a-1d2bbdd96e36"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "07af411c_c15639cb",
        "filename": "tvix/eval/src/vm.rs",
        "patchSetId": 4
      },
      "lineNbr": 234,
      "author": {
        "id": 1000034
      },
      "writtenOn": "2022-10-02T16:21:08Z",
      "side": 1,
      "message": "This is good, since `__functor` can contain another functor (which wouldn\u0027t work yet of course).",
      "revId": "3b7edd6e6bd5e11e10a1e41f1e6d01ed49142c1f",
      "serverId": "4fdfa107-4df9-4596-8e0a-1d2bbdd96e36"
    }
  ]
}