{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "a18ba7cc_cd71f787",
        "filename": "/COMMIT_MSG",
        "patchSetId": 5
      },
      "lineNbr": 9,
      "author": {
        "id": 1000001
      },
      "writtenOn": "2024-01-02T18:53:18Z",
      "side": 1,
      "message": "Still the case after the emit_warning fix?",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 9,
        "endChar": 52
      },
      "revId": "9008d988d856e10e81c92587627b6eb2025dfc4b",
      "serverId": "4fdfa107-4df9-4596-8e0a-1d2bbdd96e36"
    }
  ]
}